# Projeto Gradio ETL-Contratos

#### Esse Projeto tem o objetivo de realizar um **ETL** e **MERGE** com três tabelas utilizando o **GRADIO**

#### Preparando *Ambiente*

In [1]:
%pip install -q pandas gradio

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
import pandas as pd
import gradio as gr

In [10]:
def details_df2(df, opc):
    try:
        if opc == 'tamanho':
            display(f'Tamanho (linhas, colunas): {df.shape}')
        elif opc == 'linha':
            display(f'\nQuantidade Linhas: {df.shape[0]}')
        elif opc == 'coluna':
            nomes_colunas = df.columns.tolist()
            display(f'Quantidade de Colunas: {df.shape[1]}')
            display(f'Nomes das Colunas: {nomes_colunas}')
        elif opc == 'info':
            # Apenas chame df.info() diretamente
            print("\nInfo:")
            df.info()
        elif opc == 'head':
            # df.head() retorna um DataFrame, então imprima-o diretamente
            print("\nHead:")
            display(df.head())
        elif opc == 'isnull':
            # df.isnull().sum() retorna uma Series, então imprima-a diretamente
            print('\nIsnull:')
            display(df.isnull().sum())
        elif opc == 'todos':
            # Para 'todos', é melhor quebrar para não misturar print com retorno None
            print(f"Tamanho (linhas, colunas):{df.shape}")
            print("\nInfo:")
            df.info()
            print("\nHead:")
            print(df.head())
            print("\nIsnull:")
            print(df.isnull().sum())
        elif opc == 'config':
            print('Informações sobre configuração detals_df:\nEstá função pode mostrar detalhes no campo opc:\ntamanho: Tamanho do DF.\nlinha: Quantidade de linhas no DF.' \
            '\ncoluna: Quantidade de colunas e nomes das colunas no DF.\ninfo: Puxa informações do DF.\nhead: Puxa o head (cabeçalho) de 5 linhas do DF.\nisnull: Informa campos vazios/nulos agrupado por colunas.' \
            '\ntodos: Puxa todas as informações. Obs: Menos linha e coluna.')
        else:
            print('Erro: Informe "opc" entre tamanho, linha, coluna, info, head, isnull ou todos')
    except Exception as e:
        print(f'Erro inesperado na função detals_df: {e}')
        

def describe_df(df,opc):
    try:
        if opc == 'normal':
            display(df.describe())
        elif opc == 'object':
            display(df.describe(include='object'))
        else:
            print('Erro: Informe campo "opc" entre normal e object!')
    except Exception as e:
            print(f'Erro: Inesperado na função describe_df: {e}')

def type_columns_df(df,opc):
    try:
        if opc == 'quantitativa':
            variaveis_quantitativas = df.select_dtypes(include=['number']).columns.tolist()
            print(f"Variáveis Quantitativas: {variaveis_quantitativas}")
            return variaveis_quantitativas
        elif opc == 'qualitativa':
            variaveis_qualitativas = df.select_dtypes(include=["category","object"]).columns.tolist()
            print(f"Variáveis Qualitativa: {variaveis_qualitativas}")
            return variaveis_qualitativas
        elif opc == 'todos':
            variaveis_quantitativas = df.select_dtypes(include=['number']).columns.tolist()
            print(f"Variáveis Quantitativas: {variaveis_quantitativas}")
            variaveis_qualitativas = df.select_dtypes(include=["category","object"]).columns.tolist()
            print(f"Variáveis Qualitativa: {variaveis_qualitativas}")
            # Retorna ambas as listas
            return variaveis_quantitativas, variaveis_qualitativas
        else:
            print('Erro: Escolha no campo "opc" entre "quantitativa", "qualitativa" ou "todos"')
            return None # Retorna None explicitamente para indicar falha ou opção inválida
    except Exception as e:
            print(f'Erro: Inesperado na função tipy_columns_df: {e}')
            return None 

def renames_columns_df(df,dicionario,boolean):
    try:
        if boolean:
            df.rename(columns=dicionario,inplace=boolean)
            print('Coluna(s) informada(s) no dicionário foram renomeadas com sucesso!')
            details_df(df,'head')
        elif boolean == False:
            df_final = df.rename(columns=dicionario)
            print('Coluna(s) informada(s) no dicionário foram renomeadas com sucesso!')
            details_df(df_final,'head')
            return df_final
        else:
            print('Erro: Informe o tipo de Inplace True ou False, caso True passe variável para receber informação.')
    except Exception as e:
        print(f'Erro: Inesperado na função renames_columns_df: {e}')
        return None 

def renames_fields_df(df,coluna,dicionario):
    try:
        df[coluna] =  df[coluna].replace(dicionario)
        print(df[coluna].value_counts(dropna=False))
        return df
    except Exception as e:
        print(f'Erro: Inesperado na função renames_fields_df: {e}')
        return None

def value_counts_df(df,opc,coluna):
    try:    
        if opc == 'normal':
            print(f'\n{df[coluna].value_counts(dropna=False)}')
        elif opc == 'proporcao':
            prop = df[coluna].value_counts(normalize=True).reset_index().rename(columns={"proportion":"Proporção"}).sort_values(by="Proporção", ascending=False)
            print(f'\n{prop}')
        elif opc == 'todos':
            print(f'\n{df[coluna].value_counts(dropna=False)}')
            print(f'\n{df[coluna].value_counts(normalize=True).reset_index().rename(columns={"proportion":"Proporção"}).sort_values(by="Proporção", ascending=False)}')
        elif opc == 'config':
            print('\nInformações sobre configuração value_counts_df:\nnormal: Retorna as categorias e suas quantidades de uma determina coluna.\nproporcao:  Retorna as categorias e suas proporção de uma determina coluna.\n' \
            'todos: Retorna as categorias, suas quantidades e proporção.')
        else:
            print('\nErro: Informe a "opc" entre normal, proporcao, todos e config para mais detalhes.')
    except Exception as e:
            print(f'Erro: Inesperado na função value_counts_df: {e}')

def str_upper_df(df,column):
    try:
        df[column] = df[column].str.upper()
        print(f'\nAs categorias contidas na coluna {column} foram convertidas para maiúsculas!')
    except Exception as e:
        print(f'Erro: Inesperado na função str_upper_df: {e}')

def drop_column_df(df,columns,boolean):
    try:
        if boolean:
            df.drop(columns=columns, inplace=boolean)
            print(f'Os campos {columns} foram excluídos com sucesso!')
            details_df(df,'head')
        elif boolean == False:
            df_final = df.drop(columns=columns, inplace=boolean)
            print(f'Os campos {columns} foram excluídos com sucesso!')
            details_df(df_final,'head')
            return df_final
        else:
            print('Erro: Informe o inplace True ou False, caso True passe variável para receber informação.')
    except Exception as e:
        print(f'Erro: Inesperado na função drop_column_df: {e}')


def convert_type_df(df,opc,coluna,tipo=None):
        try:
            if opc == 'outro':
                df[coluna] = df[coluna].astype(tipo)
                print(f'A coluna {coluna}, foi alterada para {tipo} com sucesso!')
                return df[coluna]
            elif opc == 'datetime':
                df[coluna]= pd.to_datetime(df[coluna], format='%d/%m/%Y')
                print(f'A coluna {coluna}, foi alterada para datetime com sucesso!')
                return df[coluna]
            else:
                print('Erro: Por favor escolha "opc" entre outros para definir tipos Ex: int ou datetime para conversão em datas.')
        except Exception as e:
            print(f'Erro: Inesperado na função convert_type_df: {e}')
            if opc == 'datetime':
                return df

#======================================Melhorias Gemini===================================================
def details_df(df, opc):
    """
    Exibe detalhes de um DataFrame com base nas opções fornecidas.

    Args:
        df (pandas.DataFrame): O DataFrame a ser analisado.
        opc (str ou list): Uma string ou lista de strings especificando quais detalhes exibir.
                           Opções válidas: 'tamanho', 'linha', 'coluna', 'info', 'head', 'isnull', 'config'.
    """
    if isinstance(opc, str):
        opc = [opc]  # Converte a string em uma lista para uniformizar o tratamento

    for item in opc:
        try:
            if item == 'tamanho':
                print("\n--- Tamanho do DataFrame ---")
                display(f'Tamanho (linhas, colunas): {df.shape}')
            elif item == 'linha':
                print("\n--- Quantidade de Linhas ---")
                display(f'Quantidade Linhas: {df.shape[0]}')
            elif item == 'coluna':
                print("\n--- Informações de Colunas ---")
                nomes_colunas = df.columns.tolist()
                display(f'Quantidade de Colunas: {df.shape[1]}')
                display(f'Nomes das Colunas: {nomes_colunas}')
            elif item == 'info':
                print("\n--- Informações Gerais (df.info()) ---")
                df.info()
            elif item == 'head':
                print("\n--- Primeiras 5 Linhas (df.head()) ---")
                display(df.head())
            elif item == 'isnull':
                print("\n--- Valores Nulos por Coluna (df.isnull().sum()) ---")
                display(df.isnull().sum())
            elif item == 'todos':
                display(f"Tamanho (linhas, colunas): {df.shape}")
                print("\n--- Informações de Colunas ---")
                nomes_colunas = df.columns.tolist()
                display(f'Quantidade de Colunas: {df.shape[1]}')
                display(f'Nomes das Colunas: {nomes_colunas}')
                print("\n--- Informações Gerais (df.info()) ---")
                df.info()
                print("\n--- Primeiras 5 Linhas (df.head()) ---")
                display(df.head())
                print("\n--- Valores Nulos por Coluna (df.isnull().sum()) ---")
                display(df.isnull().sum())
            elif item == 'config':
                print('\n--- Configurações de Uso da Função details_df ---')
                print('Esta função pode mostrar detalhes no campo "opc".')
                print('Você pode passar uma string ou uma lista de strings com as seguintes opções:')
                print('  - "tamanho": Tamanho (linhas, colunas) do DF.')
                print('  - "linha": Quantidade de linhas no DF.')
                print('  - "coluna": Quantidade de colunas e nomes das colunas no DF.')
                print('  - "info": Informações detalhadas do DF (df.info()).')
                print('  - "head": As 5 primeiras linhas do DF (df.head()).')
                print('  - "isnull": Contagem de valores nulos por coluna (df.isnull().sum()).')
                print('  - "config": Exibe esta mensagem de configurações.')
            else:
                print(f'\n--- Opção Inválida: "{item}" ---')
                print('Opções válidas: "tamanho", "linha", "coluna", "info", "head", "isnull", "config".')
        except Exception as e:
            print(f'\n--- Erro ao processar "{item}": {e} ---')

def merge_df(df1, df2, merge_params, columns_to_drop=None):
    """
    Realiza um merge entre dois DataFrames, permite a remoção de colunas
    e exibe o cabeçalho do DataFrame resultante.

    Args:
        df1 (pd.DataFrame): O primeiro DataFrame (left).
        df2 (pd.DataFrame): O segundo DataFrame (right).
        merge_params (list): Uma lista contendo [left_on, right_on, how].
                             - left_on (str ou list): Coluna(s) para unir em df1.
                             - right_on (str ou list): Coluna(s) para unir em df2.
                             - how (str): Tipo de merge ('left', 'right', 'inner', 'outer').
        columns_to_drop (list, optional): Uma lista de nomes de colunas a serem removidas
                                           do DataFrame resultante. Padrão para None.

    Returns:
        pd.DataFrame: O DataFrame resultante da operação de merge.
    """
    if len(merge_params) != 3:
        raise ValueError("merge_params deve conter [left_on, right_on, how].")

    left_on, right_on, how = merge_params

    print(f"Realizando merge '{how}' entre DataFrames...")
    print(f"Chave(s) no primeiro DF (left_on): {left_on}")
    print(f"Chave(s) no segundo DF (right_on): {right_on}")

    try:
        df_merged = pd.merge(df1, df2, left_on=left_on, right_on=right_on, how=how)
        print("\nMerge concluído com sucesso!")
        print(f"Dimensões do DataFrame resultante: {df_merged.shape}")

        if columns_to_drop:
            print(f"\nRemovendo as seguintes colunas: {columns_to_drop}")
            # Verifica se as colunas a serem dropadas existem no DataFrame
            existing_columns = [col for col in columns_to_drop if col in df_merged.columns]
            non_existing_columns = [col for col in columns_to_drop if col not in df_merged.columns]

            if non_existing_columns:
                print(f"Atenção: As colunas {non_existing_columns} não foram encontradas no DataFrame e não serão removidas.")

            if existing_columns:
                df_merged = df_merged.drop(columns=existing_columns)
                print("Colunas removidas com sucesso!")
                print(f"Novas dimensões do DataFrame: {df_merged.shape}")
            else:
                print("Nenhuma das colunas especificadas para remoção foi encontrada no DataFrame.")

        print("\n--- Head do DataFrame Resultante ---")
        display(df_merged.head())

        return df_merged

    except Exception as e:
        print(f"Erro ao realizar a operação de merge: {e}")
        return None

In [14]:


def executar_etl_com_upload(arquivo_contratos, arquivo_datas, arquivo_empresas):

  if arquivo_contratos is None or arquivo_datas is None or arquivo_empresas is None:
    mensagem_status = "Erro: Por favor, faça o upload dos três arquivos CSV necessários para contunuar."
    return None, None, None, mensagem_status

  try: 
    # -- EXTRACAO
      tbcontratos = pd.read_csv(arquivo_contratos.name)
      tbdatas = pd.read_csv(arquivo_datas.name)
      tbempresas = pd.read_csv(arquivo_empresas.name)

      # -- TRANSFORMACAO
      # contratos_mod = tbcontratos.merge(tbempresas, left_on='fk_empresa_contratada', right_on='id_empresa', how='left')
      # contratos_mod.drop(columns=['fk_empresa_contratada','id_empresa'], inplace=True)
      contratos_mod = merge_df(tbcontratos,tbempresas,['fk_empresa_contratada','id_empresa','left'],['fk_empresa_contratada','id_empresa'])
      # contratos_mod = contratos_mod.merge(tbdatas, left_on='inicio_vigencia', right_on='id_data', how='left')
      # contratos_mod.drop(columns=['inicio_vigencia','id_data'], inplace=True)
      contratos_mod = merge_df(contratos_mod,tbdatas,['inicio_vigencia','id_data','left'],['inicio_vigencia','id_data'])
  
      # contratos_mod.rename(columns={'data':'data_inicio_vigencia'}, inplace=True)
      renames_columns_df(contratos_mod,{'data':'data_inicio_vigencia'},True)

      # contratos_mod = contratos_mod.merge(tbdatas, left_on='termino_vigencia', right_on='id_data', how='left')
      contratos_mod = merge_df(contratos_mod,tbdatas,['termino_vigencia','id_data','left'],['termino_vigencia','id_data'])
      # contratos_mod.drop(columns=['termino_vigencia','id_data'], inplace=True)
      # contratos_mod.rename(columns={'data':'data_termino_vigencia'}, inplace=True)
      renames_columns_df(contratos_mod,{'data':'data_termino_vigencia'},True)

      contratos_mod.loc[contratos_mod['data_termino_vigencia'] == '31/09/2017', 'data_termino_vigencia'] = '30/09/2017'
      contratos_mod['data_inicio_vigencia'] = pd.to_datetime(contratos_mod['data_inicio_vigencia'], format='%d/%m/%Y')
      contratos_mod['data_termino_vigencia'] = pd.to_datetime(contratos_mod['data_termino_vigencia'], format='%d/%m/%Y')
      
      contratos_mod['tempo_contrato_dias'] = (contratos_mod['data_termino_vigencia'] - contratos_mod['data_inicio_vigencia']).dt.days
      contratos_mod['tempo_contrato_dias'] = contratos_mod['tempo_contrato_dias'].astype('int64')
      contratos_finais =  contratos_mod[contratos_mod['tempo_contrato_dias']>0].copy()

      # -- ANALISE
      resumo_por_empresa = contratos_finais.groupby('nome_empresa')['valor_contrato'].agg(['sum','count']).reset_index()
      resumo_por_empresa = resumo_por_empresa.rename(columns={'sum':'valor_total', 'count':'qtd_contratos'})
      resumo_por_empresa = resumo_por_empresa.sort_values(by='valor_total', ascending=False)

      # -- CARGA
      caminho_arquivo_tratado = "contratos_tratados.csv"
      contratos_finais.to_csv(caminho_arquivo_tratado, index=False)

      return contratos_finais, resumo_por_empresa, caminho_arquivo_tratado, "Processo ETL concluído com sucesso!"

  except Exception as e:
    return None, None, None, f'Erro durante o processamento {e}'

with gr.Blocks(theme=gr.themes.Base(), title="Ferramenta ETL de Contratos") as app:
  gr.Markdown('# Ferramenta Interativa de ETL Simplificado')
  gr.Markdown('Faça o upload dos 3 arquivos CSV (contratos, datas e empresas) nos campos abaixo. Em seguida, clique no botão para processar os dados e obter o relatório final.')

  # -- INPUTS 
  with gr.Row():
    input_contratos = gr.File(label='Tabela de contratos (CSV)')
    input_datas = gr.File(label='Tabela de datas (CSV)')
    input_empresas = gr.File(label='Tabela de empresas (CSV)')

  btn_executar = gr.Button('Processar Arquivos e Gerar Relatório', variant="primary")  

  # -- OUTPUTS 
  with gr.Row():
    status_text = gr.Textbox(label='Status do Progresso', interactive=False)
    output_file = gr.File(label='Baixar o arquivo tratado')

  # -- OUTPUTS 2
  with gr.Row():
    # coluna da esquerda
    with gr.Column():
      gr.Markdown('## Resumo de Gastos por Empresa')
      output_resumo = gr.DataFrame(label='Resumo por Empresa', interactive=False)
    #coluna da direita
    with gr.Column():
      gr.Markdown('## Tabela de dados completa e tratada')
      output_dataframe_final = gr.DataFrame(label='Dados Finais', interactive=False)

  btn_executar.click(
      fn = executar_etl_com_upload,
      inputs=[input_contratos, input_datas, input_empresas],
      outputs=[output_dataframe_final, output_resumo, output_file, status_text]
  )

app.launch(debug=True)

* Running on local URL:  http://127.0.0.1:7860
* To create a public link, set `share=True` in `launch()`.

Realizando merge 'left' entre DataFrames...
Chave(s) no primeiro DF (left_on): fk_empresa_contratada
Chave(s) no segundo DF (right_on): id_empresa

Merge concluído com sucesso!
Dimensões do DataFrame resultante: (184, 9)

Removendo as seguintes colunas: ['fk_empresa_contratada', 'id_empresa']
Colunas removidas com sucesso!
Novas dimensões do DataFrame: (184, 7)

--- Head do DataFrame Resultante ---

,id_contrato,nome_contrato,objeto_contrato,valor_contrato,inicio_vigencia,termino_vigencia,nome_empresa
0,1,13/2012,Contratação de Empresa para Ministrar Curso de...,94947.23,4,32,Thomas Jefferson
1,2,Disp. Lic. 1,Prestação de serviço na confecção de Chaves,5234.00,13,33,Chaveiro City
2,3,Disp. Lic. 2,Prestação de serviço na confecção de Carimbos,1800.00,10,33,HBL Carimbos
3,4,32/2014,Serviço de Telefônia Móvel,73915.08,6,33,Claro S/A
4,5,001/2014,Publicações no Diário Oficial da União,45000.00,8,35,Imprensa Nacional

Realizando merge 'left' entre DataFrames...
Chave(s) no primeiro DF (left_on): inicio_vigencia
Chave(s) no segundo DF (right_on): id_data

Merge concluído com sucesso!
Dimensões do DataFrame resultante: (184, 9)

Removendo as seguintes colunas: ['inicio_vigencia', 'id_data']
Colunas removidas com sucesso!
Novas dimensões do DataFrame: (184, 7)

--- Head do DataFrame Resultante ---

,id_contrato,nome_contrato,objeto_contrato,valor_contrato,termino_vigencia,nome_empresa,data
0,1,13/2012,Contratação de Empresa para Ministrar Curso de...,94947.23,32,Thomas Jefferson,20/12/2014
1,2,Disp. Lic. 1,Prestação de serviço na confecção de Chaves,5234.00,33,Chaveiro City,26/02/2015
2,3,Disp. Lic. 2,Prestação de serviço na confecção de Carimbos,1800.00,33,HBL Carimbos,10/02/2015
3,4,32/2014,Serviço de Telefônia Móvel,73915.08,33,Claro S/A,01/01/2015
4,5,001/2014,Publicações no Diário Oficial da União,45000.00,35,Imprensa Nacional,27/01/2015

Coluna(s) informada(s) no dicionário foram renomeadas com sucesso!

--- Primeiras 5 Linhas (df.head()) ---

,id_contrato,nome_contrato,objeto_contrato,valor_contrato,termino_vigencia,nome_empresa,data_inicio_vigencia
0,1,13/2012,Contratação de Empresa para Ministrar Curso de...,94947.23,32,Thomas Jefferson,20/12/2014
1,2,Disp. Lic. 1,Prestação de serviço na confecção de Chaves,5234.00,33,Chaveiro City,26/02/2015
2,3,Disp. Lic. 2,Prestação de serviço na confecção de Carimbos,1800.00,33,HBL Carimbos,10/02/2015
3,4,32/2014,Serviço de Telefônia Móvel,73915.08,33,Claro S/A,01/01/2015
4,5,001/2014,Publicações no Diário Oficial da União,45000.00,35,Imprensa Nacional,27/01/2015

Realizando merge 'left' entre DataFrames...
Chave(s) no primeiro DF (left_on): termino_vigencia
Chave(s) no segundo DF (right_on): id_data

Merge concluído com sucesso!
Dimensões do DataFrame resultante: (184, 9)

Removendo as seguintes colunas: ['termino_vigencia', 'id_data']
Colunas removidas com sucesso!
Novas dimensões do DataFrame: (184, 7)

--- Head do DataFrame Resultante ---

,id_contrato,nome_contrato,objeto_contrato,valor_contrato,nome_empresa,data_inicio_vigencia,data
0,1,13/2012,Contratação de Empresa para Ministrar Curso de...,94947.23,Thomas Jefferson,20/12/2014,19/12/2015
1,2,Disp. Lic. 1,Prestação de serviço na confecção de Chaves,5234.00,Chaveiro City,26/02/2015,31/12/2015
2,3,Disp. Lic. 2,Prestação de serviço na confecção de Carimbos,1800.00,HBL Carimbos,10/02/2015,31/12/2015
3,4,32/2014,Serviço de Telefônia Móvel,73915.08,Claro S/A,01/01/2015,31/12/2015
4,5,001/2014,Publicações no Diário Oficial da União,45000.00,Imprensa Nacional,27/01/2015,26/01/2016

Coluna(s) informada(s) no dicionário foram renomeadas com sucesso!

--- Primeiras 5 Linhas (df.head()) ---

,id_contrato,nome_contrato,objeto_contrato,valor_contrato,nome_empresa,data_inicio_vigencia,data_termino_vigencia
0,1,13/2012,Contratação de Empresa para Ministrar Curso de...,94947.23,Thomas Jefferson,20/12/2014,19/12/2015
1,2,Disp. Lic. 1,Prestação de serviço na confecção de Chaves,5234.00,Chaveiro City,26/02/2015,31/12/2015
2,3,Disp. Lic. 2,Prestação de serviço na confecção de Carimbos,1800.00,HBL Carimbos,10/02/2015,31/12/2015
3,4,32/2014,Serviço de Telefônia Móvel,73915.08,Claro S/A,01/01/2015,31/12/2015
4,5,001/2014,Publicações no Diário Oficial da União,45000.00,Imprensa Nacional,27/01/2015,26/01/2016

--- Primeiras 5 Linhas (df.head()) ---

,id_contrato,nome_contrato,objeto_contrato,valor_contrato,nome_empresa,data_inicio_vigencia,data_termino_vigencia
0,1,13/2012,Contratação de Empresa para Ministrar Curso de...,94947.23,Thomas Jefferson,20/12/2014,19/12/2015
1,2,Disp. Lic. 1,Prestação de serviço na confecção de Chaves,5234.00,Chaveiro City,26/02/2015,31/12/2015
2,3,Disp. Lic. 2,Prestação de serviço na confecção de Carimbos,1800.00,HBL Carimbos,10/02/2015,31/12/2015
3,4,32/2014,Serviço de Telefônia Móvel,73915.08,Claro S/A,01/01/2015,31/12/2015
4,5,001/2014,Publicações no Diário Oficial da União,45000.00,Imprensa Nacional,27/01/2015,26/01/2016

Keyboard interruption in main thread... closing server.